/**
 * FilePath    : highlightjs-dax\src\index.ts
 * Author      : jiaopengzi
 * Blog        : https://jiaopengzi.com
 * Copyright   : Copyright (c) 2026 by jiaopengzi, All Rights Reserved.
 * Description : DAX 语言定义, 供 highlight.js 通过 registerLanguage 注册.
 */

import type { DaxHighlightApi, DaxLanguage, DaxMode } from "./types.js"

const RESERVED_WORDS = [
    "VAR",
    "RETURN",
    "DEFINE",
    "EVALUATE",
    "MEASURE",
    "ORDER",
    "BY",
    "ASC",
    "DESC",
    "BOOLEAN",
    "CURRENCY",
    "DATETIME",
    "DOUBLE",
    "INTEGER",
    "STRING",
]

const RESERVED_FUNCTIONS = [
    "ADDCALCULATEDMEMBERS",
    "AGGREGATE",
    "ALLMEMBERS",
    "ALLMEMBERS",
    "ANCESTOR",
    "ANCESTOR",
    "ANCESTORS",
    "ANCESTORS",
    "ASCENDANTS",
    "AVG",
    "AXIS",
    "BOTTOMCOUNT",
    "BOTTOMPERCENT",
    "BOTTOMSUM",
    "CALCULATIONCURRENTPASS",
    "CALCULATIONPASSVALUE",
    "CHILDREN",
    "CLOSINGPERIOD",
    "COALESCEEMPTY",
    "CORRELATION",
    "DIMENSIONS.COUNT",
    "COUNT",
    "COUNT",
    "LEVELS.COUNT",
    "COUNT",
    "COUSIN",
    "COVARIANCE",
    "COVARIANCEN",
    "CROSSJOIN",
    "CURRENT",
    "CURRENTMEMBER",
    "CURRENTORDINAL",
    "CUSTOMDATA",
    "DATAMEMBER",
    "DEFAULTMEMBER",
    "DESCENDANTS",
    "DESCENDANTS",
    "DISTINCT",
    "DISTINCTCOUNT",
    "DRILLDOWNLEVEL",
    "DRILLDOWNLEVEL",
    "DRILLDOWNLEVELBOTTOM",
    "DRILLDOWNLEVELTOP",
    "DRILLDOWNMEMBER",
    "DRILLDOWNMEMBERBOTTOM",
    "DRILLDOWNMEMBERTOP",
    "DRILLUPLEVEL",
    "DRILLUPMEMBER",
    "EXCEPT",
    "EXISTING",
    "EXISTS",
    "EXTRACT",
    "FILTER",
    "FIRSTCHILD",
    "FIRSTSIBLING",
    "GENERATE",
    "GENERATE",
    "HEAD",
    "HIERARCHIZE",
    "HIERARCHY",
    "HIERARCHY",
    "IIF",
    "INTERSECT",
    "IS",
    "ISANCESTOR",
    "ISEMPTY",
    "ISGENERATION",
    "ISLEAF",
    "ISSIBLING",
    "ITEM",
    "ITEM",
    "KPICURRENTTIMEMEMBER",
    "KPIGOAL",
    "KPISTATUS",
    "KPITREND",
    "KPIVALUE",
    "KPIWEIGHT",
    "LAG",
    "LASTCHILD",
    "LASTPERIODS",
    "LASTSIBLING",
    "LEAD",
    "LEVEL",
    "LEVELS",
    "LINKMEMBER",
    "LINREGINTERCEPT",
    "LINREGPOINT",
    "LINREGR2",
    "LINREGSLOPE",
    "LINREGVARIANCE",
    "LOOKUPCUBE",
    "MAX",
    "MEASUREGROUPMEASURES",
    "MEDIAN",
    "MEMBERS",
    "MEMBERS",
    "MEMBERTOSTR",
    "MEMBERVALUE",
    "MIN",
    "MTD",
    "NAME",
    "NAME",
    "NAME",
    "NAMETOSET",
    "NEXTMEMBER",
    "NONEMPTY",
    "NONEMPTYCROSSJOIN",
    "OPENINGPERIOD",
    "ORDER",
    "ORDINAL",
    "PARALLELPERIOD",
    "PARENT",
    "PERIODSTODATE",
    "PREDICT",
    "PREVMEMBER",
    "PROPERTIES",
    "QTD",
    "RANK",
    "ROLLUPCHILDREN",
    "SETTOARRAY",
    "SETTOSTR",
    "SIBLINGS",
    "STDDEV",
    "STDDEVP",
    "STDEVP",
    "STDEVP",
    "STRIPCALCULATEDMEMBERS",
    "STRTOMEMBER",
    "STRTOSET",
    "STRTOTUPLE",
    "STRTOVALUE",
    "SUBSET",
    "SUM",
    "TAIL",
    "TOGGLEDRILLSTATE",
    "TOPCOUNT",
    "TOPPERCENT",
    "TOPSUM",
    "TUPLETOSTR",
    "UNION",
    "UNIQUENAME",
    "UNIQUENAME",
    "UNIQUENAME",
    "UNKNOWNMEMBER",
    "UNORDER",
    "VALIDMEASURE",
    "VALUE",
    "VARIANCE",
    "VARIANCEP",
    "VARP",
    "VISUALTOTALS",
    "WTD",
    "YTD",
    "DATE",
    "DATEDIFF",
    "DATEVALUE",
    "DAY",
    "EDATE",
    "EOMONTH",
    "HOUR",
    "MINUTE",
    "MONTH",
    "NETWORKDAYS",
    "NOW",
    "QUARTER",
    "SECOND",
    "TIME",
    "TIMEVALUE",
    "TODAY",
    "UTCNOW",
    "UTCTODAY",
    "WEEKDAY",
    "WEEKNUM",
    "YEAR",
    "YEARFRAC",
    "BITAND",
    "BITLSHIFT",
    "BITOR",
    "BITRSHIFT",
    "BITXOR",
    "ACCRINT",
    "ACCRINTM",
    "AMORDEGRC",
    "AMORLINC",
    "COUPDAYBS",
    "COUPDAYS",
    "COUPDAYSNC",
    "COUPNCD",
    "COUPNUM",
    "COUPPCD",
    "CUMIPMT",
    "CUMPRINC",
    "DB",
    "DDB",
    "DISC",
    "DOLLARDE",
    "DOLLARFR",
    "DURATION",
    "EFFECT",
    "FV",
    "INTRATE",
    "IPMT",
    "ISPMT",
    "MDURATION",
    "NOMINAL",
    "NPER",
    "ODDFPRICE",
    "ODDFYIELD",
    "ODDLPRICE",
    "ODDLYIELD",
    "PDURATION",
    "PMT",
    "PPMT",
    "PRICE",
    "PRICEDISC",
    "PRICEMAT",
    "PV",
    "RATE",
    "RECEIVED",
    "RRI",
    "SLN",
    "SYD",
    "TBILLEQ",
    "TBILLPRICE",
    "TBILLYIELD",
    "VDB",
    "YIELD",
    "YIELDDISC",
    "YIELDMAT",
    "COMBINEVALUES",
    "CONTAINS",
    "CONTAINSROW",
    "CONVERT",
    "CUSTOMDATA",
    "ERROR",
    "HASONEFILTER",
    "HASONEVALUE",
    "ISBLANK",
    "ISCROSSFILTERED",
    "ISEMPTY",
    "ISERROR",
    "ISEVEN",
    "ISFILTERED",
    "ISINSCOPE",
    "ISLOGICAL",
    "ISNONTEXT",
    "ISNUMBER",
    "ISODD",
    "ISSUBTOTAL",
    "ISTEXT",
    "USERCULTURE",
    "USERNAME",
    "USEROBJECTID",
    "USERPRINCIPALNAME",
    "AND",
    "COALESCE",
    "FALSE",
    "IF",
    "IF.EAGER",
    "IFERROR",
    "NAMEOF",
    "NOT",
    "OR",
    "SWITCH",
    "TRUE",
    "ABS",
    "ACOS",
    "ACOSH",
    "ACOT",
    "ACOTH",
    "ASIN",
    "ASINH",
    "ATAN",
    "ATANH",
    "BETA.DIST",
    "BETA.INV",
    "CEILING",
    "CHISQ.DIST",
    "CHISQ.DIST.RT",
    "CHISQ.INV",
    "CHISQ.INV.RT",
    "COMBIN",
    "COMBINA",
    "CONFIDENCE.NORM",
    "CONFIDENCE.T",
    "COS",
    "COSH",
    "COT",
    "COTH",
    "CURRENCY",
    "DEGREES",
    "EVEN",
    "EXP",
    "EXPON.DIST",
    "FACT",
    "FLOOR",
    "GCD",
    "INT",
    "ISO.CEILING",
    "LCM",
    "LN",
    "LOG",
    "LOG10",
    "MOD",
    "MROUND",
    "NORM.DIST",
    "NORM.INV",
    "NORM.S.DIST",
    "NORM.S.INV",
    "ODD",
    "PERMUT",
    "PI",
    "POISSON.DIST",
    "POWER",
    "QUOTIENT",
    "RADIANS",
    "RAND",
    "RANDBETWEEN",
    "ROUND",
    "ROUNDDOWN",
    "ROUNDUP",
    "SIGN",
    "SIN",
    "SINH",
    "SQRT",
    "SQRTPI",
    "T.DIST",
    "T.DIST.2T",
    "T.DIST.RT",
    "T.INV",
    "T.INV.2T",
    "TAN",
    "TANH",
    "TRUNC",
    "BLANK",
    "CONCATENATE",
    "CONCATENATEX",
    "CONTAINSSTRING",
    "CONTAINSSTRINGEXACT",
    "EVALUATEANDLOG",
    "EXACT",
    "FIND",
    "FIXED",
    "FORMAT",
    "LEFT",
    "LEN",
    "LOWER",
    "MID",
    "REPLACE",
    "REPT",
    "RIGHT",
    "SEARCH",
    "SUBSTITUTE",
    "TOCSV",
    "TOJSON",
    "TRIM",
    "UNICHAR",
    "UNICODE",
    "UPPER",
    "VALUE",
    "CLOSINGBALANCEMONTH",
    "CLOSINGBALANCEQUARTER",
    "CLOSINGBALANCEYEAR",
    "DATEADD",
    "DATESBETWEEN",
    "DATESINPERIOD",
    "DATESMTD",
    "DATESQTD",
    "DATESYTD",
    "ENDOFMONTH",
    "ENDOFQUARTER",
    "ENDOFYEAR",
    "FIRSTDATE",
    "FIRSTNONBLANK",
    "FIRSTNONBLANKVALUE",
    "LASTDATE",
    "LASTNONBLANK",
    "LASTNONBLANKVALUE",
    "NEXTDAY",
    "NEXTMONTH",
    "NEXTQUARTER",
    "NEXTYEAR",
    "OPENINGBALANCEMONTH",
    "OPENINGBALANCEQUARTER",
    "OPENINGBALANCEYEAR",
    "PARALLELPERIOD",
    "PREVIOUSDAY",
    "PREVIOUSMONTH",
    "PREVIOUSQUARTER",
    "PREVIOUSYEAR",
    "SAMEPERIODLASTYEAR",
    "STARTOFMONTH",
    "STARTOFQUARTER",
    "STARTOFYEAR",
    "TOTALMTD",
    "TOTALQTD",
    "TOTALYTD",
    "ADDCOLUMNS",
    "ALL",
    "ALLCROSSFILTERED",
    "ALLEXCEPT",
    "ALLNOBLANKROW",
    "ALLSELECTED",
    "CALCULATE",
    "CALCULATETABLE",
    "CALENDAR",
    "CALENDARAUTO",
    "CROSSFILTER",
    "CROSSJOIN",
    "DATATABLE",
    "DETAILROWS",
    "DISTINCT",
    "EARLIER",
    "EARLIEST",
    "EXCEPT",
    "FILTER",
    "FILTERS",
    "GENERATE",
    "GENERATEALL",
    "GENERATESERIES",
    "IGNORE",
    "INTERSECT",
    "ISAFTER",
    "ISONORAFTER",
    "ISSELECTEDMEASURE",
    "KEEPFILTERS",
    "LOOKUPVALUE",
    "NATURALINNERJOIN",
    "NATURALLEFTOUTERJOIN",
    "RELATED",
    "RELATEDTABLE",
    "REMOVEFILTERS",
    "ROW",
    "SELECTCOLUMNS",
    "SELECTEDMEASURE",
    "SELECTEDMEASUREFORMATSTRING",
    "SELECTEDMEASURENAME",
    "SELECTEDVALUE",
    "SUMMARIZE",
    "TOPN",
    "TREATAS",
    "UNION",
    "USERELATIONSHIP",
    "VALUES",
    "SUM",
    "SUMX",
    "PATH",
    "PATHCONTAINS",
    "PATHITEM",
    "PATHITEMREVERSE",
    "PATHLENGTH",
    "ADDMISSINGITEMS",
    "CURRENTGROUP",
    "GROUPBY",
    "NONVISUAL",
    "ROLLUP",
    "ROLLUPADDISSUBTOTAL",
    "ROLLUPGROUP",
    "ROLLUPISSUBTOTAL",
    "SAMPLE",
    "SUBSTITUTEWITHINDEX",
    "SUMMARIZECOLUMNS",
    "AVERAGE",
    "AVERAGEA",
    "AVERAGEX",
    "COUNT",
    "COUNTA",
    "COUNTAX",
    "COUNTBLANK",
    "COUNTROWS",
    "COUNTX",
    "DISTINCTCOUNT",
    "DISTINCTCOUNTNOBLANK",
    "DIVIDE",
    "GEOMEAN",
    "GEOMEANX",
    "LINEST",
    "LINESTX",
    "MAX",
    "MAXA",
    "MAXX",
    "MEDIAN",
    "MEDIANX",
    "MIN",
    "MINA",
    "MINX",
    "PERCENTILE.EXC",
    "PERCENTILE.INC",
    "PERCENTILEX.EXC",
    "PERCENTILEX.INC",
    "PRODUCT",
    "PRODUCTX",
    "RANK.EQ",
    "RANKX",
    "STDEV.P",
    "STDEV.S",
    "STDEVX.P",
    "STDEVX.S",
    "VAR.P",
    "VAR.S",
    "VARX.P",
    "VARX.S",
    "XIRR",
    "XNPV",
    "COLUMNSTATISTICS",
    "INDEX",
    "OFFSET",
    "ORDERBY",
    "PARTITIONBY",
    "WINDOW",
]

/**
 * 创建 DAX 语言定义, 供 highlight.js 通过 registerLanguage 注册.
 * @param hljs highlight.js 提供的运行时 API, 用于组合正则与生成注释模式.
 * @returns 返回符合 highlight.js 语言工厂约定的 DAX 定义对象.
 * @throws 不主动抛出错误, 但当传入的 hljs API 不完整时, 注册或高亮过程可能失败.
 */
export default function dax(hljs: DaxHighlightApi): DaxLanguage {
    const regex = hljs.regex
    const reservedWordGuard = regex.either(...RESERVED_WORDS)

    const stringMode: DaxMode = {
        scope: "string",
        variants: [{ match: /"[\s\S]*?"/ }],
    }

    const tableNameMode: DaxMode = {
        scope: "symbol",
        begin: /'/,
        end: /'/,
    }

    const columnNameMode: DaxMode = {
        scope: "symbol",
        begin: /\[/,
        end: /\]/,
    }

    const functionMode: DaxMode = {
        scope: "built_in",
        begin: regex.concat(/\b/, regex.either(...RESERVED_FUNCTIONS), /\b/),
    }

    const keywordMode: DaxMode = {
        scope: "keyword",
        begin: regex.concat(/\b/, regex.either(...RESERVED_WORDS), /\b/),
    }

    const measureNameMode: DaxMode = {
        scope: "title",
        begin: new RegExp(`^(?!\\s*(?:${reservedWordGuard})\\b)[^\\s=][^\\r\\n=]*(?=\\s*=)`, "m"),
    }

    const variableMode: DaxMode = {
        scope: "variable",
        begin: /(?<!\S)[A-Za-z_][A-Za-z0-9_]*(?=\s|$|[\W])/,
    }

    const operatorMode: DaxMode = {
        scope: "operator",
        begin: /[-+*/=%^~]|&&?|\|\|?|!=?|<(?:=>?|<|>)?|>[>=]?/,
        relevance: 0,
    }

    const punctuationMode: DaxMode = {
        scope: "punctuation",
        begin: /[()[\]{}]/,
        relevance: 0,
    }

    const numberMode: DaxMode = {
        scope: "number",
        begin: /\b\d+(?:\.\d+)?\b/,
    }

    const lineCommentMode = hljs.COMMENT("//", /$/)

    return {
        name: "DAX",
        case_insensitive: true,
        contains: [
            hljs.C_BLOCK_COMMENT_MODE,
            lineCommentMode,
            measureNameMode,
            keywordMode,
            functionMode,
            tableNameMode,
            columnNameMode,
            stringMode,
            operatorMode,
            punctuationMode,
            numberMode,
            variableMode,
        ],
    }
}
