/**
 * FilePath    : highlightjs-dax\src\index.ts
 * Author      : jiaopengzi
 * Blog        : https://jiaopengzi.com
 * Copyright   : Copyright (c) 2026 by jiaopengzi, All Rights Reserved.
 * Description : DAX 语言定义, 供 highlight.js 通过 registerLanguage 注册.
 */

import type { DaxHighlightApi, DaxLanguage, DaxMode } from "./types.js"

const RESERVED_WORDS = [
    "VAR",
    "RETURN",
    "DEFINE",
    "EVALUATE",
    "MEASURE",
    "ORDER",
    "BY",
    "ASC",
    "DESC",
    "BOOLEAN",
    "CURRENCY",
    "DATETIME",
    "DOUBLE",
    "INTEGER",
    "STRING",
]

const RESERVED_FUNCTIONS = [
    "ABS",
    "ACCRINT",
    "ACCRINTM",
    "ACOS",
    "ACOSH",
    "ACOT",
    "ACOTH",
    "ADDCOLUMNS",
    "ADDMISSINGITEMS",
    "ALL",
    "ALLCROSSFILTERED",
    "ALLEXCEPT",
    "ALLNOBLANKROW",
    "ALLSELECTED",
    "AMORDEGRC",
    "AMORLINC",
    "AND",
    "APPROXIMATEDISTINCTCOUNT",
    "ASIN",
    "ASINH",
    "ATAN",
    "ATANH",
    "AVERAGE",
    "AVERAGEA",
    "AVERAGEX",
    "BETA.DIST",
    "BETA.INV",
    "BITAND",
    "BITLSHIFT",
    "BITOR",
    "BITRSHIFT",
    "BITXOR",
    "BLANK",
    "CALCULATE",
    "CALCULATETABLE",
    "CALENDAR",
    "CALENDARAUTO",
    "CEILING",
    "CHISQ.DIST",
    "CHISQ.DIST.RT",
    "CHISQ.INV",
    "CHISQ.INV.RT",
    "CLOSINGBALANCEMONTH",
    "CLOSINGBALANCEQUARTER",
    "CLOSINGBALANCEWEEK",
    "CLOSINGBALANCEYEAR",
    "COALESCE",
    "COLLAPSE",
    "COLLAPSEALL",
    "COLUMNSTATISTICS",
    "COMBIN",
    "COMBINA",
    "COMBINEVALUES",
    "CONCATENATE",
    "CONCATENATEX",
    "CONFIDENCE.NORM",
    "CONFIDENCE.T",
    "CONTAINS",
    "CONTAINSROW",
    "CONTAINSSTRING",
    "CONTAINSSTRINGEXACT",
    "CONVERT",
    "COS",
    "COSH",
    "COT",
    "COTH",
    "COUNT",
    "COUNTA",
    "COUNTAX",
    "COUNTBLANK",
    "COUNTROWS",
    "COUNTX",
    "COUPDAYBS",
    "COUPDAYS",
    "COUPDAYSNC",
    "COUPNCD",
    "COUPNUM",
    "COUPPCD",
    "CROSSFILTER",
    "CROSSJOIN",
    "CUMIPMT",
    "CUMPRINC",
    "CURRENCY",
    "CURRENTGROUP",
    "CUSTOMDATA",
    "DATATABLE",
    "DATE",
    "DATEADD",
    "DATEDIFF",
    "DATESBETWEEN",
    "DATESINPERIOD",
    "DATESMTD",
    "DATESQTD",
    "DATESWTD",
    "DATESYTD",
    "DATEVALUE",
    "DAY",
    "DB",
    "DDB",
    "DEGREES",
    "DETAILROWS",
    "DISC",
    "DISTINCT",
    "DISTINCTCOUNT",
    "DISTINCTCOUNTNOBLANK",
    "DIVIDE",
    "DOLLARDE",
    "DOLLARFR",
    "DURATION",
    "EARLIER",
    "EARLIEST",
    "EDATE",
    "EFFECT",
    "ENDOFMONTH",
    "ENDOFQUARTER",
    "ENDOFWEEK",
    "ENDOFYEAR",
    "EOMONTH",
    "ERROR",
    "EVALUATEANDLOG",
    "EVEN",
    "EXACT",
    "EXCEPT",
    "EXP",
    "EXPAND",
    "EXPANDALL",
    "EXPON.DIST",
    "EXTERNALMEASURE",
    "FACT",
    "FALSE",
    "FILTER",
    "FILTERS",
    "FIND",
    "FIRST",
    "FIRSTDATE",
    "FIRSTNONBLANK",
    "FIRSTNONBLANKVALUE",
    "FIXED",
    "FLOOR",
    "FORMAT",
    "FV",
    "GCD",
    "GENERATE",
    "GENERATEALL",
    "GENERATESERIES",
    "GEOMEAN",
    "GEOMEANX",
    "GROUPBY",
    "HASONEFILTER",
    "HASONEVALUE",
    "HOUR",
    "IF",
    "IF.EAGER",
    "IFERROR",
    "IGNORE",
    "INDEX",
    "INFO.ALTERNATEOFDEFINITIONS",
    "INFO.ANNOTATIONS",
    "INFO.ATTRIBUTEHIERARCHIES",
    "INFO.ATTRIBUTEHIERARCHYSTORAGES",
    "INFO.CALCDEPENDENCY",
    "INFO.CALCULATIONGROUPS",
    "INFO.CALCULATIONITEMS",
    "INFO.CATALOGS",
    "INFO.CHANGEDPROPERTIES",
    "INFO.COLUMNPARTITIONSTORAGES",
    "INFO.COLUMNPERMISSIONS",
    "INFO.COLUMNS",
    "INFO.COLUMNSTORAGES",
    "INFO.CSDLMETADATA",
    "INFO.CULTURES",
    "INFO.DATACOVERAGEDEFINITIONS",
    "INFO.DATASOURCES",
    "INFO.DELTATABLEMETADATASTORAGES",
    "INFO.DEPENDENCIES",
    "INFO.DETAILROWSDEFINITIONS",
    "INFO.DICTIONARYSTORAGES",
    "INFO.EXCLUDEDARTIFACTS",
    "INFO.EXPRESSIONS",
    "INFO.EXTENDEDPROPERTIES",
    "INFO.FORMATSTRINGDEFINITIONS",
    "INFO.FUNCTIONS",
    "INFO.GENERALSEGMENTMAPSEGMENTMETADATASTORAGES",
    "INFO.GROUPBYCOLUMNS",
    "INFO.HIERARCHIES",
    "INFO.HIERARCHYSTORAGES",
    "INFO.KPIS",
    "INFO.LEVELS",
    "INFO.LINGUISTICMETADATA",
    "INFO.MEASURES",
    "INFO.MODEL",
    "INFO.OBJECTTRANSLATIONS",
    "INFO.PARQUETFILESTORAGES",
    "INFO.PARTITIONS",
    "INFO.PARTITIONSTORAGES",
    "INFO.PERSPECTIVECOLUMNS",
    "INFO.PERSPECTIVEHIERARCHIES",
    "INFO.PERSPECTIVEMEASURES",
    "INFO.PERSPECTIVES",
    "INFO.PERSPECTIVETABLES",
    "INFO.PROPERTIES",
    "INFO.QUERYGROUPS",
    "INFO.REFRESHPOLICIES",
    "INFO.RELATEDCOLUMNDETAILS",
    "INFO.RELATIONSHIPINDEXSTORAGES",
    "INFO.RELATIONSHIPS",
    "INFO.RELATIONSHIPSTORAGES",
    "INFO.ROLEMEMBERSHIPS",
    "INFO.ROLES",
    "INFO.SEGMENTMAPSTORAGES",
    "INFO.SEGMENTSTORAGES",
    "INFO.STORAGEFILES",
    "INFO.STORAGEFOLDERS",
    "INFO.STORAGETABLECOLUMNS",
    "INFO.STORAGETABLECOLUMNSEGMENTS",
    "INFO.STORAGETABLES",
    "INFO.TABLEPERMISSIONS",
    "INFO.TABLES",
    "INFO.TABLESTORAGES",
    "INFO.VARIATIONS",
    "INFO.VIEW.COLUMNS",
    "INFO.VIEW.MEASURES",
    "INFO.VIEW.RELATIONSHIPS",
    "INFO.VIEW.TABLES",
    "INT",
    "INTERSECT",
    "INTRATE",
    "IPMT",
    "ISAFTER",
    "ISATLEVEL",
    "ISBLANK",
    "ISBOOLEAN",
    "ISCROSSFILTERED",
    "ISCURRENCY",
    "ISDATETIME",
    "ISDECIMAL",
    "ISDOUBLE",
    "ISEMPTY",
    "ISERROR",
    "ISEVEN",
    "ISFILTERED",
    "ISINSCOPE",
    "ISINT64",
    "ISINTEGER",
    "ISLOGICAL",
    "ISNONTEXT",
    "ISNUMBER",
    "ISNUMERIC",
    "ISO.CEILING",
    "ISODD",
    "ISONORAFTER",
    "ISPMT",
    "ISSELECTEDMEASURE",
    "ISSTRING",
    "ISSUBTOTAL",
    "ISTEXT",
    "KEEPFILTERS",
    "LAST",
    "LASTDATE",
    "LASTNONBLANK",
    "LASTNONBLANKVALUE",
    "LCM",
    "LEFT",
    "LEN",
    "LINEST",
    "LINESTX",
    "LN",
    "LOG",
    "LOG10",
    "LOOKUP",
    "LOOKUPVALUE",
    "LOOKUPWITHTOTALS",
    "LOWER",
    "MATCHBY",
    "MAX",
    "MAXA",
    "MAXX",
    "MDURATION",
    "MEDIAN",
    "MEDIANX",
    "MID",
    "MIN",
    "MINA",
    "MINUTE",
    "MINX",
    "MOD",
    "MONTH",
    "MOVINGAVERAGE",
    "MROUND",
    "NAMEOF",
    "NATURALINNERJOIN",
    "NATURALJOINUSAGE",
    "NATURALLEFTOUTERJOIN",
    "NETWORKDAYS",
    "NEXT",
    "NEXTDAY",
    "NEXTMONTH",
    "NEXTQUARTER",
    "NEXTWEEK",
    "NEXTYEAR",
    "NOMINAL",
    "NONVISUAL",
    "NORM.DIST",
    "NORM.INV",
    "NORM.S.DIST",
    "NORM.S.INV",
    "NOT",
    "NOW",
    "NPER",
    "ODD",
    "ODDFPRICE",
    "ODDFYIELD",
    "ODDLPRICE",
    "ODDLYIELD",
    "OFFSET",
    "OPENINGBALANCEMONTH",
    "OPENINGBALANCEQUARTER",
    "OPENINGBALANCEWEEK",
    "OPENINGBALANCEYEAR",
    "OR",
    "ORDERBY",
    "PARALLELPERIOD",
    "PARTITIONBY",
    "PATH",
    "PATHCONTAINS",
    "PATHITEM",
    "PATHITEMREVERSE",
    "PATHLENGTH",
    "PDURATION",
    "PERCENTILE.EXC",
    "PERCENTILE.INC",
    "PERCENTILEX.EXC",
    "PERCENTILEX.INC",
    "PERMUT",
    "PI",
    "PMT",
    "POISSON.DIST",
    "POWER",
    "PPMT",
    "PREVIOUS",
    "PREVIOUSDAY",
    "PREVIOUSMONTH",
    "PREVIOUSQUARTER",
    "PREVIOUSWEEK",
    "PREVIOUSYEAR",
    "PRICE",
    "PRICEDISC",
    "PRICEMAT",
    "PRODUCT",
    "PRODUCTX",
    "PV",
    "QUARTER",
    "QUOTIENT",
    "RADIANS",
    "RAND",
    "RANDBETWEEN",
    "RANGE",
    "RANK",
    "RANK.EQ",
    "RANKX",
    "RATE",
    "RECEIVED",
    "RELATED",
    "RELATEDTABLE",
    "REMOVEFILTERS",
    "REPLACE",
    "REPT",
    "RIGHT",
    "ROLLUP",
    "ROLLUPADDISSUBTOTAL",
    "ROLLUPGROUP",
    "ROLLUPISSUBTOTAL",
    "ROUND",
    "ROUNDDOWN",
    "ROUNDUP",
    "ROW",
    "ROWNUMBER",
    "RRI",
    "RUNNINGSUM",
    "SAMEPERIODLASTYEAR",
    "SAMPLE",
    "SAMPLEAXISWITHLOCALMINMAX",
    "SAMPLECARTESIANPOINTSBYCOVER",
    "SEARCH",
    "SECOND",
    "SELECTCOLUMNS",
    "SELECTEDMEASURE",
    "SELECTEDMEASUREFORMATSTRING",
    "SELECTEDMEASURENAME",
    "SELECTEDVALUE",
    "SIGN",
    "SIN",
    "SINH",
    "SLN",
    "SQRT",
    "SQRTPI",
    "STARTOFMONTH",
    "STARTOFQUARTER",
    "STARTOFWEEK",
    "STARTOFYEAR",
    "STDEV.P",
    "STDEV.S",
    "STDEVX.P",
    "STDEVX.S",
    "SUBSTITUTE",
    "SUBSTITUTEWITHINDEX",
    "SUM",
    "SUMMARIZE",
    "SUMMARIZECOLUMNS",
    "SUMX",
    "SWITCH",
    "SYD",
    "T.DIST",
    "T.DIST.2T",
    "T.DIST.RT",
    "T.INV",
    "T.INV.2T",
    "TABLEOF",
    "TAN",
    "TANH",
    "TBILLEQ",
    "TBILLPRICE",
    "TBILLYIELD",
    "TIME",
    "TIMEVALUE",
    "TOCSV",
    "TODAY",
    "TOJSON",
    "TOPN",
    "TOPNSKIP",
    "TOTALMTD",
    "TOTALQTD",
    "TOTALWTD",
    "TOTALYTD",
    "TREATAS",
    "TRIM",
    "TRUE",
    "TRUNC",
    "UNICHAR",
    "UNICODE",
    "UNION",
    "UPPER",
    "USERCULTURE",
    "USERELATIONSHIP",
    "USERNAME",
    "USEROBJECTID",
    "USERPRINCIPALNAME",
    "UTCNOW",
    "UTCTODAY",
    "VALUE",
    "VALUES",
    "VAR.P",
    "VAR.S",
    "VARX.P",
    "VARX.S",
    "VDB",
    "WEEKDAY",
    "WEEKNUM",
    "WINDOW",
    "XIRR",
    "XNPV",
    "YEAR",
    "YEARFRAC",
    "YIELD",
    "YIELDDISC",
    "YIELDMAT",
]

/**
 * 创建 DAX 语言定义, 供 highlight.js 通过 registerLanguage 注册.
 * @param hljs highlight.js 提供的运行时 API, 用于组合正则与生成注释模式.
 * @returns 返回符合 highlight.js 语言工厂约定的 DAX 定义对象.
 * @throws 不主动抛出错误, 但当传入的 hljs API 不完整时, 注册或高亮过程可能失败.
 */
export default function dax(hljs: DaxHighlightApi): DaxLanguage {
    const regex = hljs.regex
    const reservedWordGuard = regex.either(...RESERVED_WORDS)

    const stringMode: DaxMode = {
        scope: "string",
        variants: [{ match: /"[\s\S]*?"/ }],
    }

    const tableNameMode: DaxMode = {
        scope: "symbol",
        begin: /'/,
        end: /'/,
    }

    const columnNameMode: DaxMode = {
        scope: "symbol",
        begin: /\[/,
        end: /\]/,
    }

    const functionMode: DaxMode = {
        scope: "built_in",
        begin: regex.concat(/\b/, regex.either(...RESERVED_FUNCTIONS), /\b/),
    }

    const keywordMode: DaxMode = {
        scope: "keyword",
        begin: regex.concat(/\b/, regex.either(...RESERVED_WORDS), /\b/),
    }

    const measureNameMode: DaxMode = {
        scope: "title",
        begin: new RegExp(`^(?!\\s*(?:${reservedWordGuard})\\b)[^\\s=][^\\r\\n=]*(?=\\s*=)`, "m"),
    }

    const variableMode: DaxMode = {
        scope: "variable",
        begin: /(?<!\S)[A-Za-z_][A-Za-z0-9_]*(?=\s|$|[\W])/,
    }

    const operatorMode: DaxMode = {
        scope: "operator",
        begin: /[-+*/=%^~]|&&?|\|\|?|!=?|<(?:=>?|<|>)?|>[>=]?/,
        relevance: 0,
    }

    const punctuationMode: DaxMode = {
        scope: "punctuation",
        begin: /[()[\]{}]/,
        relevance: 0,
    }

    const numberMode: DaxMode = {
        scope: "number",
        begin: /\b\d+(?:\.\d+)?\b/,
    }

    const lineCommentMode = hljs.COMMENT("//", /$/)

    return {
        name: "DAX",
        case_insensitive: true,
        contains: [
            hljs.C_BLOCK_COMMENT_MODE,
            lineCommentMode,
            measureNameMode,
            keywordMode,
            functionMode,
            tableNameMode,
            columnNameMode,
            stringMode,
            operatorMode,
            punctuationMode,
            numberMode,
            variableMode,
        ],
    }
}
